sonar.verbose=true
sonar.organization=subir-test-key
sonar.projectKey=subir-test-key_test
sonar.projectName=test
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources =.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
